<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" child.project.url.inherit.append.path="true" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.github.arosecra</groupId>
    <artifactId>brooke</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>brooke-angular</artifactId>
  <packaging>pom</packaging>
  <name>brooke-angular</name>
  <description>Angular frontend for brooke</description>
  <build>
    <finalName>brooke</finalName>
    <plugins>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <configuration>
          <filesets>
            <fileset>
              <directory>.</directory>
              <includes>
                <include>.angular/</include>
                <include>node_modules/</include>
                <include>dist/</include>
              </includes>
            </fileset>
          </filesets>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>NPM Install</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <inherited>true</inherited>
            <configuration>
              <executable>npm</executable>
              <arguments>
                <argument>install</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>NPM Compile</id>
            <phase>compile</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <inherited>true</inherited>
            <configuration>
              <executable>npm</executable>
              <arguments>
                <argument>run</argument>
                <argument>build</argument>
              </arguments>
            </configuration>
          </execution>
          <execution>
            <id>NPM Package</id>
            <phase>package</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <inherited>true</inherited>
            <configuration>
              <executable>npm</executable>
              <arguments>
                <argument>run</argument>
                <argument>package</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
